services:
  mentoring-service:
    image: ${IMAGE}:${IMAGE_TAG:-latest}
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "9006:9006"
    restart: unless-stopped
