services:
  mentoring-service:
    image: ${IMAGE}:${IMAGE_TAG:-latest}
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "9006:9006"
    volumes:
      - ./ssl/kafka.truststore.jks:/app/ssl/kafka.truststore.jks:ro
      - mentoring-logs:/app/logs
    restart: unless-stopped
    networks:
      - goggles-network

volumes:
  mentoring-logs:

networks:
  goggles-network:
    external: true
