services:
  mentoring-service:
    image: ${IMAGE}:${IMAGE_TAG:-latest}
    env_file: .env
    ports:
      - "9006:9006"
    volumes:
      - ./ssl/kafka.truststore.jks:/app/ssl/kafka.truststore.jks:ro
    restart: unless-stopped
