spring:
  application:
    name: mentoring-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - "optional:configserver: "
      - "optional:file:.env[.properties]"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/goggles
    username: ${DB_USERNAME:goggles}
    password: ${DB_PASSWORD:goggles}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
        default_schema: mentoring

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

resilience4j:
  circuitbreaker:
    instances:
      hub-server:
        failure-rate-threshold: 50          # 회로 차단 기준
        minimum-number-of-calls: 5          # 최소 통계 횟수
        sliding-window-size: 10             # 최근 호출 기준 개수
        wait-duration-in-open-state: 10s    # 차단 후 복구 시도까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3  # 복구 시도 시 허용되는 호출 수

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  config:
    activate:
      on-profile: local

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: create
management:
  tracing:
    sampling:
      probability: 0.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true